### PR TITLE
Adding new files

### PR DESCRIPTION
**Pull request by alvaroordonez**
Created this feature branch for any changes throughout the project. Cloned this main repo to my local machine and added .gitignore with the appropriate files to well .... ignore.

### CODE REVIEW

**Comment by alvaroordonez** [comment]
Reopening this PR, trying to get in the habit of doing things right.

**Review by Jecockrell3 — APPROVED** [review]
looks good

**Review by Jecockrell3 — APPROVED** [review]
looks good

**Comment by Jecockrell3** [comment]
I hit approve, go ahead and merge

Then github said it had an issue and made me refresh then it put my comment twice.

**Pull request merged**
